### ISSUE TITLE
Scroll description

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/guidelines#87]
It would be useful to work on the open scroll issues (no, this is not only an issue says "work on the issues"....), and add the information in the guidelines, possibly in a new page for scroll descriptions. (Taking care, as always, to be very explicit that these would be POSSIBLITIES of encoding, not a catalogue of mandatory parameters to check off)
I am assigning myself for now and would be willing to do it, but not disappointed if someone else feels more qualified.
@DenisNosnitsin1970 @DariaElagina

**Comment by DariaElagina** [comment]
I completely agree, there are some points we have to discuss here, especially concerning locus and layout:
1) Do we want to use 1r/ 1v to distinguishe between the face side and the riverse side? I have some more scrolls wich have texts/additions on their reverse side. I was not using this terminology just because it was to much stuck to codices in my head.
2) The scrolls are sewn mostly of several parchment strips, do we want to number them 1,2,3 accordingly?
3) Concerning the locus: I used to put into the note the information on lines. But I think that the way of encoding that Dorothea has proposed is much better:
`<locus from="1r" n="1"></locus>
                    <locus to="1r" n="14"></locus>`

**Comment by thea-m** [comment]
I will open individual issues for the single questions in the documentation guidelines (I think it's good to have all these discussions in one place, so that they are easier to search and find for everyone).

**Comment by PietroLiuzzo** [comment]
once #103 is merged, this issue can also be closed
