### ISSUE TITLE
Pages on the structure of records

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/guidelines#92]
Again and again, new users express the very strong desire to have pages on the guidelines which clarify the order of the elements in all records (manuscripts being the most complicated ones). OUr guidelines are very fragmented and the TEI guidelines are apparently not so useful and not evident to use. It apparently would be very useful to work on this. https://betamasaheft.eu/Guidelines/?id=structure was a start but is not sufficient.

**Comment by PietroLiuzzo** [comment]
A desire of prescriptivness in early stages of encoding experience is natural, but not useful on the long term, when people risk to fixate themselves on an order of items which is instead not relevant. While the order of the elements in msDesc _is_ fixed, this is undoubtfully explained in chapter 10 of the TEI Guidelines, and repeating this in our guidelines would not be of much help IMHO. On the other side, most schema based XML software will be able to populate lists of available elements in the order in which they may occur directly in the editor. What additional kind of order and structure would be useful to the understanding of how to encode is very unclear for me. if these strong desires could be formulated directly in this public space with examples we could try and find out how to make our page more helpful, at the moment I would not even know where to start to improve and in which direction...

**Comment by thea-m** [comment]
Yes, I understand. The reason why I never took any steps in this direction was that this sorts itself out as people become more familiar with encoding and look at example files. 

But at the beginning, I understand that it really is confusing for someone who wants to work on the binding description in a manuscript, goes to the guidelines and finds the binding description page, which gives no indication where in the manuscript this element belongs.

If we decide to do something, what I could imagine would be basically reproducing the table of contents of the TEI manuscript guidelines and listing under each section the pages concerning them which exist in our guidelines (while of course keeping all the current ways of navigating the guidelines, since many pages refer to phenomena not limited to one specific section). And there are already pages in the guidelines adressing this, such as https://betamasaheft.eu/Guidelines/?id=manuscriptDescription or https://betamasaheft.eu/Guidelines/?id=manuscriptPhysDescription. 

(Not major, but still, since it came up in a training today: the order of foliation, collation and condition allowed by our schema does not correspond to the order of their presentation in the TEI guidelines. That was unhelpful, as the point I had tried to make by going to the TEI guidelines was "here you will find a good structured overview of the elements which will clear all confusion!"...)

**Comment by PietroLiuzzo** [comment]
@thea-m please could you help me to understand your last statement? which order is required by our schema? there is no explicit statement about that which I can recall. the content model has ( support?, extent?, foliation*, collation?, condition? ), and the [TEI guidelines follow the same order](https://tei-c.org/release/doc/tei-p5-doc/en/html/MS.html#msph1) and this should be the order also in our files, and in facts I could not find any which has a different order. If this sort of information should be reproduced also in the guidelines, we can pick it from the schema and display it in each elements page. We are not currently displaying content models, because they are already in the TEI guidelines which are linked above. There could be scope for this as we do have some more specific models. But I still do not see where is the difference between our order and the TEI guidelines order? or are you speaking of the order of presentation of these contents in our guidelines which has collation before foliation? I do not think it was ever meant to follow any order, but the only variation I find is that the collation information is discussed in a separate page and this line comes at the top instead of after foliation. I am sure I am missing something. help!

**Comment by thea-m** [comment]
I was talking about the order of presentation in the TEI guidelines, which is collation, foliation, condition
![image](https://user-images.githubusercontent.com/19650382/80716102-8ae46300-8af7-11ea-94f9-5afa81ee8cbe.png)
Our schema wants, as the content model (which I had not checked) as you said, foliation, collation, condition.

**Comment by PietroLiuzzo** [comment]
I think you can propose this change to reflect the content model to the TEI group. I am not sure that in the GL page the content model is used, perhaps it is just a list. For our guidelines, what we can do is reproduce the content model on the element page.

**Comment by thea-m** [comment]
I think reproducing the content model sounds good. It would give people a clear place to look for when these questions arrise without offering some kind of empty file with all possible elements to be filled in. Thank you!
